version: '3'
services:
  odoo_web:
    image: odoo:12.0
    restart: always
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    environment:
    - USER=${PGUSER}
    - PASSWORD=${PGPASSWORD}
    volumes:
      - odoo_odoo-web-config:/etc/odoo
      - /share/docker-appdata/odoo/addons:/mnt/extra-addons
      - /share/docker-appdata/odoo/data:/var/lib/odoo
    resources:
      limits:
        cpus: '0.5'
        memory: 1G
      reservations:
        cpus: '0.1'
        memory: 50M
  odoo_db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      - POSTGRES_USER={PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_odoo-db:/var/lib/postgresql
      - odoo_odoo-db-data:/var/lib/postgresql/data
    resources:
      limits:
        cpus: '0.5'
        memory: 1G
      reservations:
        cpus: '0.1'
        memory: 50M

volumes:
  odoo_odoo-web-config:
  odoo_odoo-db:
  odoo_odoo-db-data:
